---
- name: Add certbot packages
  community.general.snap:
    name: certbot
    classic: yes

- name: Run certbot
  command: >-
    certbot --apache --noninteractive --agree-tos --redirect
    --email {{ certbot_admin_email }}
    -d {{ certbot_domains | join(',') }}

- name: Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  when: certbot_auto_renew
